local pipe_subgroup = "energy-pipe-distribution"

if settings.startup["flow-control-new-group"].value then
	pipe_subgroup = "pipe-distribution"
end

data:extend({
	{
		name = "concrete-pipe-elbow",
		icon = "__xtreme-flow-control__/graphics/icon/concrete-pipe-elbow.png",
		icon_size = 64,
		place_result = "concrete-pipe-elbow",
		stack_size = 50,
		subgroup = pipe_subgroup,
		order = "b[pipe]-a[pipe]l",
		type = "item",
	},
	{
		name = "concrete-pipe-straight",
		icon = "__xtreme-flow-control__/graphics/icon/concrete-pipe-straight.png",
		icon_size = 64,
		place_result = "concrete-pipe-straight",
		stack_size = 50,
		subgroup = pipe_subgroup,
		order = "b[pipe]-a[pipe]m",
		type = "item",
	},
	{
		name = "concrete-pipe-t-junction",
		icon = "__xtreme-flow-control__/graphics/icon/concrete-pipe-t-junction.png",
		icon_size = 64,
		place_result = "concrete-pipe-t-junction",
		stack_size = 50,
		subgroup = pipe_subgroup,
		order = "b[pipe]-a[pipe]n",
		type = "item",
	},
	{
		name = "copper-pipe-elbow",
		icon = "__xtreme-flow-control__/graphics/icon/copper-pipe-elbow.png",
		icon_size = 64,
		place_result = "copper-pipe-elbow",
		stack_size = 50,
		subgroup = pipe_subgroup,
		order = "b[pipe]-a[pipe]f",
		type = "item",
	},
	{
		name = "copper-pipe-straight",
		icon = "__xtreme-flow-control__/graphics/icon/copper-pipe-straight.png",
		icon_size = 64,
		place_result = "copper-pipe-straight",
		stack_size = 50,
		subgroup = pipe_subgroup,
		order = "b[pipe]-a[pipe]g",
		type = "item",
	},
	{
		name = "copper-pipe-t-junction",
		icon = "__xtreme-flow-control__/graphics/icon/copper-pipe-t-junction.png",
		icon_size = 64,
		place_result = "copper-pipe-t-junction",
		stack_size = 50,
		subgroup = pipe_subgroup,
		order = "b[pipe]-a[pipe]h",
		type = "item",
	},
	{
		name = "plastic-pipe-elbow",
		icon = "__xtreme-flow-control__/graphics/icon/plastic-pipe-elbow.png",
		icon_size = 64,
		place_result = "plastic-pipe-elbow",
		stack_size = 50,
		subgroup = pipe_subgroup,
		order = "b[pipe]-a[pipe]o",
		type = "item",
	},
	{
		name = "plastic-pipe-straight",
		icon = "__xtreme-flow-control__/graphics/icon/plastic-pipe-straight.png",
		icon_size = 64,
		place_result = "plastic-pipe-straight",
		stack_size = 50,
		subgroup = pipe_subgroup,
		order = "b[pipe]-a[pipe]p",
		type = "item",
	},
	{
		name = "plastic-pipe-t-junction",
		icon = "__xtreme-flow-control__/graphics/icon/plastic-pipe-t-junction.png",
		icon_size = 64,
		place_result = "concrete-pipe-t-junction",
		stack_size = 50,
		subgroup = pipe_subgroup,
		order = "b[pipe]-a[pipe]q",
		type = "item",
	},
	{
		name = "stone-pipe-elbow",
		icon = "__xtreme-flow-control__/graphics/icon/stone-pipe-elbow.png",
		icon_size = 64,
		place_result = "stone-pipe-elbow",
		stack_size = 50,
		subgroup = pipe_subgroup,
		order = "b[pipe]-a[pipe]c",
		type = "item",
	},
	{
		name = "stone-pipe-straight",
		icon = "__xtreme-flow-control__/graphics/icon/stone-pipe-straight.png",
		icon_size = 64,
		place_result = "stone-pipe-straight",
		stack_size = 50,
		subgroup = pipe_subgroup,
		order = "b[pipe]-a[pipe]d",
		type = "item",
	},
	{
		name = "stone-pipe-t-junction",
		icon = "__xtreme-flow-control__/graphics/icon/stone-pipe-t-junction.png",
		icon_size = 64,
		place_result = "stone-pipe-t-junction",
		stack_size = 50,
		subgroup = pipe_subgroup,
		order = "b[pipe]-a[pipe]e",
		type = "item",
	},
})
