data:extend({
	{
		type = "recipe",
		name = "concrete-pipe-straight",
		enabled = false,
		energy_required = 0.01,
		ingredients = { { "concrete-pipe", 1 } },
		result = "concrete-pipe-straight",
	},
	{
		type = "recipe",
		name = "concrete-pipe-t-junction",
		enabled = false,
		energy_required = 0.01,
		ingredients = { { "concrete-pipe", 1 } },
		result = "concrete-pipe-t-junction",
	},
	{
		type = "recipe",
		name = "concrete-pipe-elbow",
		enabled = false,
		energy_required = 0.01,
		ingredients = { { "concrete-pipe", 1 } },
		result = "concrete-pipe-elbow",
	},
    {
		type = "recipe",
		name = "copper-pipe-straight",
		enabled = true,
		energy_required = 0.01,
		ingredients = { { "copper-pipe", 1 } },
		result = "copper-pipe-straight",
	},
	{
		type = "recipe",
		name = "copper-pipe-t-junction",
		enabled = true,
		energy_required = 0.01,
		ingredients = { { "copper-pipe", 1 } },
		result = "copper-pipe-t-junction",
	},
	{
		type = "recipe",
		name = "copper-pipe-elbow",
		enabled = true,
		energy_required = 0.01,
		ingredients = { { "copper-pipe", 1 } },
		result = "copper-pipe-elbow",
	},
    {
		type = "recipe",
		name = "plastic-pipe-straight",
		enabled = false,
		energy_required = 0.01,
		ingredients = { { "plastic-pipe", 1 } },
		result = "plastic-pipe-straight",
	},
	{
		type = "recipe",
		name = "plastic-pipe-t-junction",
		enabled = false,
		energy_required = 0.01,
		ingredients = { { "plastic-pipe", 1 } },
		result = "plastic-pipe-t-junction",
	},
	{
		type = "recipe",
		name = "plastic-pipe-elbow",
		enabled = false,
		energy_required = 0.01,
		ingredients = { { "plastic-pipe", 1 } },
		result = "plastic-pipe-elbow",
	},
    {
		type = "recipe",
		name = "stone-pipe-straight",
		enabled = true,
		energy_required = 0.01,
		ingredients = { { "stone-pipe", 1 } },
		result = "stone-pipe-straight",
	},
	{
		type = "recipe",
		name = "stone-pipe-t-junction",
		enabled = true,
		energy_required = 0.01,
		ingredients = { { "stone-pipe", 1 } },
		result = "stone-pipe-t-junction",
	},
	{
		type = "recipe",
		name = "stone-pipe-elbow",
		enabled = true,
		energy_required = 0.01,
		ingredients = { { "stone-pipe", 1 } },
		result = "stone-pipe-elbow",
	},
})
